#!/bin/sh

[[ -r ~/.profile ]] && source ~/.profile

if [[ -z "$EDITOR" && -z "$VISUAL" ]]; then
	echo -n "Which editor do you prefer? (e.g. nano, vim, emacs): "
	read EDITOR
	export EDITOR
	echo "export EDITOR='$EDITOR'" >> ~/.editor
	echo "export VISUAL='$VISUAL'" >> ~/.editor
fi

if ! git config user.email > /dev/null; then
	git config --global --edit
fi

if [[ "$EDITOR" == 'vim' ]]; then
	if [[ ! -e ~/.vim/colors/felipec.vim ]]; then
		mkdir -p ~/.vim/colors/
		curl "https://raw.githubusercontent.com/felipec/vim-felipec/master/colors/felipec.vim" -o ~/.vim/colors/felipec.vim
	fi
fi
