#!/bin/sh

if [[ -e ~/.config/profile ]]; then
	source ~/.config/profile
else
	echo -n "Which editor do you prefer? (e.g. nano, vim, emacs): "
	read EDITOR
	[[ -z "$EDITOR" ]] && EDITOR='vim'
	export EDITOR
	[[ "$EDITOR" == 'vim' ]] && VISUAL='gvim'
	echo "export EDITOR='$EDITOR'" >> ~/.config/profile
	echo "export VISUAL='$VISUAL'" >> ~/.config/profile
fi

if ! git config user.email > /dev/null; then
	cat <<-EOF > ~/.gitconfig
	[user]
	  name =
	  email =
	EOF
	git config --file ~/.gitconfig --edit
fi

if [[ "$EDITOR" == 'vim' ]]; then
	if [[ ! -e ~/.vim/colors/felipec.vim ]]; then
		mkdir -p ~/.vim/colors/
		curl "https://raw.githubusercontent.com/felipec/vim-felipec/master/colors/felipec.vim" -o ~/.vim/colors/felipec.vim
	fi
fi

dot-checkout

if command -v xfconf-load > /dev/null; then
	echo -n "Do you want to load the Xfce configuration? (y/N): "
	read load
	[[ "$load" == 'y' ]] && xfconf-load ~/.config/xfconf-helper/config.yml
fi
