#!/bin/bash

dot-checkout

if [[ -e ~/.config/profile ]]; then
	source ~/.config/profile
else
	echo -n "Which editor do you prefer? (e.g. nano, vim, emacs): "
	read EDITOR
	[[ -z "$EDITOR" ]] && EDITOR='vim'
	export EDITOR
	cat <<-EOF > ~/.config/profile
	export EDITOR='$EDITOR'
	export VISUAL='$VISUAL'
	EOF
fi

if ! git config user.email > /dev/null; then
	echo "Git configuration"
	echo -n "What's your name? (e.g. John Doe): "
	read NAME
	git config --file ~/.gitconfig user.name "$NAME"
	echo -n "What's your email? (e.g. john@doe.com): "
	read EMAIL
	git config --file ~/.gitconfig user.email "$EMAIL"
fi

if [[ "$EDITOR" == 'vim' ]]; then
	if [[ ! -e ~/.vim/colors/felipec.vim ]]; then
		mkdir -p ~/.vim/colors/
		curl "https://raw.githubusercontent.com/felipec/vim-felipec/master/colors/felipec.vim" -o ~/.vim/colors/felipec.vim
	fi
fi

if command -v xfconf-load > /dev/null; then
	echo -n "Do you want to load the Xfce configuration? (y/N): "
	read load
	[[ "$load" == 'y' ]] && xfconf-load ~/.config/xfconf-helper/config.yml
fi
